run: all
	./sem_prioridade.out 10 1 
	# ./prioridade_escritora.out 1 10
	# ./sem_inanicao.out 3 4
all:
	gcc -o sem_prioridade.out sem_prioridade.c -lpthread -Wall --pedantic
	# gcc -o prioridade_escritora.out prioridade_escritora.c -lpthread -Wall --pedantic
	# gcc -o sem_inanicao.out sem_inanicao.c -lpthread -Wall --pedantic